services:

  php:
    image: ghcr.io/zainmajeedch/laravel-docker-php:1.1

    environment:
      APP_DEBUG: "false"
      APP_ENV: production
      APP_KEY: base64:Y5q2Fd1OVGyc5CrjPyURKPV8zK4zazlKSP5kpePVdyQ=
      APP_URL: http://localhost:8082

      CACHE_STORE: redis

      DB_CONNECTION: mysql
      DB_DATABASE: laravel
      DB_HOST: mariadb
      DB_PASSWORD: laravel_password
      DB_PORT: "3306"
      DB_USERNAME: laravel

      QUEUE_CONNECTION: database

      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: "6379"

      SESSION_DRIVER: database

    networks:
      - laravel-network

    volumes:
      - laravel_storage:/var/www/html/storage

    deploy:
      replicas: 1

      labels:
        swarm.autoscaler.enabled: "true"
        swarm.autoscaler.min: "1"
        swarm.autoscaler.max: "5"
        swarm.autoscaler.metric: "cpu"
        swarm.autoscaler.target: "50"

      resources:
        limits:
          cpus: "1"
          memory: 512M

      restart_policy:
        condition: on-failure

    healthcheck:
      test:
        - CMD
        - php-fpm
        - -t
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s


  nginx:
    image: ghcr.io/zainmajeedch/laravel-docker-nginx:2.0

    ports:
      - "8082:80"

    networks:
      - laravel-network

    volumes:
      - laravel_storage:/var/www/html/storage:ro

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure

  mariadb:
    image: mariadb:11

    environment:
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: laravel_password
      MARIADB_ROOT_PASSWORD: root_password

    networks:
      - laravel-network

    volumes:
      - laravel_mariadb_data:/var/lib/mysql

    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - --connect
        - --innodb_initialized
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  redis:
    image: redis:alpine

    networks:
      - laravel-network

    volumes:
      - laravel_redis_data:/data

    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  laravel-network:
    external: true
    name: laravel-swarm-network


volumes:

  laravel_storage:
    external: true
    name: laravel-docker_laravel_storage

  laravel_mariadb_data:
    external: true
    name: laravel-docker_laravel_mariadb_data

  laravel_redis_data:
    external: true
    name: laravel-docker_laravel_redis_data
